name = "QuantumOperatorDefinitions"
uuid = "826dd319-6fd5-459a-a990-3a4f214664bf"
version = "0.2.8"
authors = ["ITensor developers <support@itensor.org> and contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
GradedArrays = "bc96ca6e-b7c8-4bb6-888e-c93f838762c2"
ITensorBase = "4795dd04-0d67-49bb-8f44-b89c448a1dc7"
NamedDimsArrays = "60cbd0c0-df58-4cb7-918c-6f5607b73fde"

[extensions]
QuantumOperatorDefinitionsGradedArraysExt = ["BlockArrays", "GradedArrays"]
QuantumOperatorDefinitionsITensorBaseExt = ["ITensorBase", "GradedArrays", "NamedDimsArrays"]

[compat]
BlockArrays = "1.3.0"
GradedArrays = "0.4"
ITensorBase = "0.2"
LinearAlgebra = "1.10"
NamedDimsArrays = "0.7"
Random = "1.10"
julia = "1.10"
